### ISSUE TITLE
more precise repo description

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/VariantAlly#1]
Consider changing "Enhance Chinese Wikipedia's variant support" to "Enhance Chinese Wikipedia's language variant support". I found "variant" by itself to be unclear. Thank you.

**Comment by NovemLinguae** [comment]
After reading some more, maybe also consider...

"Enhance switching between Chinese character sets on Chinese Wikipedia"

**Comment by diskdance** [comment]
I have changed it. Can you please check if this is OK?

**Comment by NovemLinguae** [comment]
Looks good. Thanks!
