### ISSUE TITLE
Not confined to Wikipedia alone

### ISSUE THREAD

**Issue by AnYiEE** [wikimedia-gadgets/VariantAlly#2]
Within the realm of Chinese websites employing MediaWiki, it is inevitable that numerous sites encounter the quandary of guiding users towards selecting variations.

Is it feasible in certain instances to eschew hard coding and render this tool more versatile?

**Comment by diskdance** [comment]
@AnYiEE This tool is specifically for Wikimedia wiki's use case where modifying backends is not feasible. I believe for other sites, the better workaround is to store variant preferences in the cookie and serve accordingly at backends.

**Comment by AnYiEE** [comment]
One thing that needs clarification is that even in China, websites using cookies to track users and send them back to the server must still take into account and may be restricted by relevant policies (such as compliance), whereas localStorage is comparatively less troublesome.

**Comment by diskdance** [comment]
Yes, but I still think modifying backends should be recommend over this script. Feel free to comment here if any websites in practice need to use this script.

**Comment by AnYiEE** [comment]
It seems to work well on other MediaWiki sites. https://github.com/qiuwenbaike/QiuwenGadgets/commit/cd35f3f
