### ISSUE TITLE
请求添加「不再提醒」选项 / Request for a “Do Not Remind” option

### ISSUE THREAD

**Issue by pennzht** [wikimedia-gadgets/VariantAlly#3]
你好！感谢你为中文维基百科贡献这一工具。我有一点请求，希望能够考虑。

在浏览器语言非中文、未登录的情况下，访问中文维基百科会显示这一对话框。在关闭对话框之后，再访问任何页面，对话框仍然会出现，<strong>要求读者</strong>必须选择一种简体或繁体选项，即便屡次关闭对话框仍然每次出现。

这有点困扰我，因为我一直习惯阅读「不转换」的原文（以及匿名阅读）。我希望读到的文字与作者所写完全一致，而不希望读到一篇被算法自动繁简转换过的文字，因为繁简转换无法永远达到 100% 准确度，仍然可能出现误转换。对我而言，「能够无损阅读原文」比「避免繁简混杂」更重要。而且我相信，这一需求[不仅限于我](https://phabricator.wikimedia.org/T282929)。

故，我想请求在对话框中添加一个「不再提醒」的选项（正常文字大小即可），经选择后不再要求读者选择变体。

我已阅读[互助客栈上的说明](https://zh.wikipedia.org/zh/Wikipedia:%E4%BA%92%E5%8A%A9%E5%AE%A2%E6%A0%88/%E6%8A%80%E6%9C%AF#%E4%B8%AD%E6%96%87%E5%8F%98%E4%BD%93%E5%8A%A9%E6%89%8B%E5%B0%8F%E5%B7%A5%E5%85%B7%EF%BC%88VariantAlly%EF%BC%89)，但未能解决问题。

敬盼复信；再次感谢。💙

<details><summary>English</summary>

Hello! I would like to thank you for providing this tool for Chinese Wikipedia. I have a request which I hope you could consider.

This dialog appears every time when the reader visits Chinese Wikipedia, if the browser's language is not Chinese and the reader is not logged in. After the reader closes the dialog, it still shows up on every page, demanding that the reader select a Simplified or Traditional variant option, even when the reader repeatedly closes the dialog.

This behavior affects me, as I prefer reading the __original text, without conversion__ (as well as reading anonymously). I wish to read the article verbatim, as it was written by the author, instead of an output of an algorithmic conversion — for variant conversion in Chinese is not 100% accurate but still prone to misconversions. I consider the ability to read the original losslessly more important than avoiding a mixed-variant article, and I believe I'm [not the only one with this need](https://phabricator.wikimedia.org/T282929).

So I wish that a new option, “Do not remind me again”, be added to the dialog, which hides the dialog permanently so that the reader is prompted no more. The option may display at a normal font size.

I have already read [the description on Village Pump](https://zh.wikipedia.org/zh/Wikipedia:%E4%BA%92%E5%8A%A9%E5%AE%A2%E6%A0%88/%E6%8A%80%E6%9C%AF#%E4%B8%AD%E6%96%87%E5%8F%98%E4%BD%93%E5%8A%A9%E6%89%8B%E5%B0%8F%E5%B7%A5%E5%85%B7%EF%BC%88VariantAlly%EF%BC%89), but it didn't solve the problem.

I look forward to your response. Thank you again. 💙

</details>

**Comment by diskdance** [comment]
您好，

非常感谢您的建议。小工具在开发的时候主要照顾的是普通读者的需求，您的情况确实没有考虑到。

如果在小工具中添加不再提醒的选项的话，只能通过LocalStorage等方式保存状态，这种方法在无痕模式下并不可靠。

之前考虑过通过浏览器插件或者用户脚本来保留变体设置（[打算做引导界面但是并未实现](https://github.com/wikimedia-gadgets/VariantAlly/blob/763217f40eb07fc72ce496ee39084d6a500caa47/gadgets/variant-ally-dialog/src/components/VariantDialog.vue#L176)）。正好借着这个issue，我写了个[用户脚本](https://greasyfork.org/en/scripts/480760-%E5%BC%BA%E5%88%B6%E6%8C%87%E5%AE%9A%E4%B8%AD%E6%96%87%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91%E9%A1%B5%E9%9D%A2%E8%AF%AD%E8%A8%80%E5%8F%98%E4%BD%93)，不知道能否解决此问题？

**Comment by pennzht** [comment]
感谢回复！

这个现象在非无痕模式中也是存在的（如果读者未登录）。请问可否通过类似方式用 `localStorage` 实现？

据我所知，主流浏览器只有在无痕模式关闭后才会清空 cookies 和 `localStorage`。如果在无痕模式中选择「不再提醒」，就只需要<strong>每次开启</strong>无痕模式关闭<strong>一次</strong>对话框，我可以接受。上一版本的「小蓝条」也给了用户「不再提示」这一选择。

我知道脚本可以在一台电脑上避免这一问题，但仍然希望请求从根源上完善这一工具。模态对话框如果没有「不再提醒」的选项，会十分影响用户体验。因为对话框中没有帮助链接，我在看到这一对话框后，在维基百科的帮助页面中找了很久才找到本 GitHub 仓库；甚至因为不了解维基的组织结构（我刚注册账户不久），曾一度到 [Phabricator](https://phabricator.wikimedia.org/) 上求助。如果其他读者也有这个苦恼，他们可能也要寻找很久，甚至可能找不到帮助。

恳请能够考虑这一请求。再次感谢 💙

**Comment by AnYiEE** [comment]
脚本无法判断浏览器是否处在无痕模式下，但鉴于可能确实有不少人想主动忽略提示，或许可以考虑提供范围时间内不再提示的选项，mw.storage正好有相关方法。之所以是暂时关闭，是因为考虑到作出决定的人可能其实还不太清楚对应选择的含义，所以留一个反悔的余地。

**Comment by pennzht** [comment]
> 脚本无法判断浏览器是否处在无痕模式下，但鉴于可能确实有不少人想主动忽略提示，或许可以考虑提供范围时间内不再提示的选项，mw.storage正好有相关方法。之所以是暂时关闭，是因为考虑到作出决定的人可能其实还不太清楚对应选择的含义，所以留一个反悔的余地。

如果一定要添加「暂时关闭」的选项，可不可以同时 <strong>也</strong> 添加一个「永久关闭」的选项？

对话框中已经指出了该选择的意义（避免繁简混杂），如果用户仍然坚持，说明用户确实有需要，宜尊重用户选择。

**Comment by diskdance** [comment]
刚刚和 @AnYiEE 讨论了一下，打算添加这个选项。用localStorage来实现，所以如果在无痕浏览模式的中的话还是会弹出。由于Safari在无痕模式下每个标签页的Cookie和localStorage都是隔离的，所以会完全无效。

如果想要完全不显示弹窗的话有两个选项，第一个是通过上方的用户脚本，第二个是可以让小工具识别特殊的query param（如`?va-variant=zh`）并自动把本地变体设置为`zh`，然后把这个链接保存到书签，每次使用无痕模式先打开书签就可以。

**Comment by pennzht** [comment]
> 刚刚和 @AnYiEE 讨论了一下，打算添加这个选项。用localStorage来实现，所以如果在无痕浏览模式的中的话还是会弹出。由于Safari在无痕模式下每个标签页的Cookie和localStorage都是隔离的，所以会完全无效。
> 
> 如果想要完全不显示弹窗的话有两个选项，第一个是通过上方的用户脚本，第二个是可以让小工具识别特殊的query param（如`?va-variant=zh`）并自动把本地变体设置为`zh`，然后把这个链接保存到书签，每次使用无痕模式先打开书签就可以。

十分感谢你的帮助！！期待更新。

（如果一定要添加「暂不提醒 / 稍后提醒」选项，也恳求同时提供「不再提醒」选项。谢谢！）

**Comment by diskdance** [comment]
以下为重新设计的弹窗，这样可以尽量避免遮挡内容。滑动页面或者鼠标移出弹窗，弹窗就会自动关闭（临时关闭），而点击关闭按钮则为永久关闭。

您可以使用非中文浏览器到[测试站点](https://zh.wikipedia.beta.wmflabs.org)测试，如果有什么建议的话欢迎提出，谢谢。

![desktop](https://github.com/wikimedia-gadgets/VariantAlly/assets/106794417/6c2e451d-71c9-441c-8ab2-61e581e80c71)
![mobile](https://github.com/wikimedia-gadgets/VariantAlly/assets/106794417/90cdd59e-2188-4939-b732-8e1f75eeb495)

**Comment by pennzht** [comment]
> 以下为重新设计的弹窗，这样可以尽量避免遮挡内容。滑动页面或者鼠标移出弹窗，弹窗就会自动关闭（临时关闭），而点击关闭按钮则为永久关闭。

谢谢！我有个建议：
* 「鼠标移出弹窗，弹窗立刻关闭」这个处理方法容易导致误操作。因为用户移动鼠标时不一定第一次移动就准确定位，可能出现鼠标滑过头又移动回来的情况。我第一次试用的时候，弹窗在我想关闭它之前就先关闭了，未能让我 opt out。其他用户也可能会有「弹窗还没看清就不见了」的困惑。
  - 是否可以分成「关闭窗口」和「不再提醒」两个选择？前者 = 「暂不提醒」。

十分感谢！敬盼复信。

**Comment by diskdance** [comment]
小工具有收集一些关于用户互动的统计数据，打算部署之后根据统计数据再讨论是否要更改这个行为。

> 是否可以分成「关闭窗口」和「不再提醒」两个选择？前者 = 「暂不提醒」。

主要问题在于，我希望弹窗能保持简洁（做这个小工具的原因之一就是嫌小蓝条丑），并且在目前的设计下临时关闭比永久关闭容易触发得多（即使鼠标移出弹窗不关闭也是如此），正好可以区分两种行为，所以个人还是倾向于只留一个永久关闭的按钮。

**Comment by diskdance** [comment]
统计数据表明桌面端的关闭率高于移动端，目前已经关闭了“鼠标移出弹窗，弹窗立刻关闭”行为。

由于issue标题所述问题已经解决，现关闭此issue。

**Comment by pennzht** [comment]
谢谢你的帮助！我在 zh.wikipedia.org 上测试了一下，用户体验很好。
（过去一个月因私事未能复信，请谅解。）

再次感谢作者对中文维基百科的贡献。💙
