### ISSUE TITLE
rewriteAnchors doesn't check if the <a> tag had an 'href'

### ISSUE THREAD

**Issue by edg2s** [wikimedia-gadgets/VariantAlly#4]
OOUI buttons, such as those used in VE, use `<a>` tags without an href.

This script appears to rewrite the empty href back to the tag as `<a href="undefined">`, which means clicking on any tool in VE navigates you off the page.

Reported here: https://phabricator.wikimedia.org/T352501

**Comment by diskdance** [comment]
@edg2s Both from TypeScript or my own testing shows that for an <a> without href accessing href returns an empty string.

The `undefined` is caused by Jon (WMF)'s hotfix which causes `rewriteLink` to return undefined when an exception is thrown.

**Comment by edg2s** [comment]
Sorry about that. Do you need help applying the fixes to this repo?

cc @jdlrobson

**Comment by diskdance** [comment]
I have asked admins to apply hot fixes for now. I'm currently working on various improvements on this project and I hope to deploy all the improvements to the wiki in the near future. Thanks!

**Comment by jdlrobson** [comment]
Sorry for my failed fix!  I can confirm the error is no longer appearing in production.
<img width="977" alt="Screenshot 2023-12-01 at 9 05 11 AM" src="https://github.com/wikimedia-gadgets/VariantAlly/assets/148752/36e416b5-e6ca-4d93-bcf2-d1d45c5a6f2d">

Thanks @esanders for patching the production version.
