### ISSUE TITLE
Upstream hotfixes applied on-wiki

### ISSUE THREAD

**Issue by edg2s** [wikimedia-gadgets/VariantAlly#6]
A few changes have been made directly to the wiki that should be upstream here to keep the code in sync:

https://zh.wikipedia.org/w/index.php?title=MediaWiki:Gadget-VariantAlly.js&action=history

**Comment by diskdance** [comment]
Yes, but I have been working on a lot of improvements on this gadget locally and the code structure has been changed dramatically since then.

I'm sure all the fixes here have been applied and rebased on my local branch. I will publish the code here once I'm finished with the improvements.
